# 5.4 自定义层
举例来说，研究人员发明了专门用于处理图像、文本、序列数据和执行动态规划的层。
有时候，我们会遇到或发明一个在深度学习框架中还不存在的层

## 5.4.1 不带参数的层

In [20]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    """从输入中减去均值"""
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [21]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [22]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [23]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.7253e-09, grad_fn=<MeanBackward0>)

## 5.4.2 带参数的层
我们可以使用内置函数来创建参数，这些函数提供一些基本的管理功能，比如管理访问、初始化、共享、保存和加载模型参数

In [24]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [25]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.5039,  0.1027, -0.4174],
        [ 0.2472,  0.2713, -0.9121],
        [-1.7167,  0.0529, -0.8661],
        [ 0.1407, -1.4553, -0.0826],
        [-1.6618, -0.9771, -1.7475]], requires_grad=True)

In [26]:
linear(torch.rand(2, 5))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
# 我们可以利用自定义层，构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [4.2325]])

## 练习

In [28]:
# 设计一个接受输入并计算张量降维的层

# 设计一个返回输入数据的傅立叶系数前半部分的层。