In [1]:
#5.5 读写文件


In [2]:
## 5.5.1 加载和保存张量


import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [3]:
# 张量形式的列表
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [5]:
# 张量形式的自字典
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [6]:
## 5.5.2 加载和保存模型参数
# 注意保存下来的参数但不包括架构，架构需要另外指定
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2,20))
Y = net(X)
Y

tensor([[-0.1212,  0.1382,  0.0801,  0.5137,  0.0084, -0.0692, -0.2594,  0.2442,
          0.0429, -0.4134],
        [ 0.0935,  0.4525,  0.2949,  0.3657,  0.2023, -0.0616, -0.1961, -0.2219,
          0.0118, -0.6100]], grad_fn=<AddmmBackward0>)

In [7]:
torch.save(net.state_dict(), 'mlp.params')

In [8]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [9]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])