In [12]:
import torch
from torch import nn
from d2l import torch as d2l

# 多输入的情况
def corr2d_multi_in(X, K):
    return sum(d2l.corr2d(x, k) for x, k in zip (X, K))

In [13]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
                [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])

K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])
print("X.shape = ", X.shape)
print("K.shape = ", K.shape)
corr2d_multi_in(X, K)

X.shape =  torch.Size([2, 3, 3])
K.shape =  torch.Size([2, 2, 2])


tensor([[ 56.,  72.],
        [104., 120.]])

In [14]:
def corr2d_multi_in_out(X, K):
    return torch.stack([corr2d_multi_in(X, K) for k in K], 0) # 在0这个维度
print(K)
print(K.shape)

tensor([[[0., 1.],
         [2., 3.]],

        [[1., 2.],
         [3., 4.]]])
torch.Size([2, 2, 2])


In [15]:
K = torch.stack((K, K+1, K+2), 0)
print(K)
print(K.shape)

tensor([[[[0., 1.],
          [2., 3.]],

         [[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]],

         [[2., 3.],
          [4., 5.]]],


        [[[2., 3.],
          [4., 5.]],

         [[3., 4.],
          [5., 6.]]]])
torch.Size([3, 2, 2, 2])


In [16]:
corr2d_multi_in_out(X, K)

ValueError: too many values to unpack (expected 2)

In [17]:
# 1*1 卷积
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape((c_o, c_i))
    Y = torch.matmul(K, X) # reshape 的目的是 矩阵乘法
    return Y.reshape((c_o, h, w))

X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(X, K)
print(Y1)

tensor([[[-0.0891,  0.5142,  0.5971],
         [-0.4658,  0.0527, -0.2557],
         [-0.1592,  0.1553,  0.2115]],

        [[ 0.4927, -2.4730, -3.0184],
         [ 2.3149, -0.3252,  2.1515],
         [-1.3791,  0.3617, -0.4053]]])
